### ISSUE TITLE
Ask about the source code in grabbing QT messages.

### ISSUE THREAD

**Issue by LWYgut** [KDAB/GammaRay#1006]
Thank you for the wonderful open source code!
The GammaRay software is very useful and has caused me great interest in reading the source code to learn it, but I have recently encountered two difficulties and would like to ask you about them.

Q1：Recently I was reading through your code and found that there are a lot of folders and I can't tell what each of them does, can you briefly describe what each folder does?

Q2：When I use GammaRay software, I found that it can capture the changing content of the same control. And for any control, it can go directly to the corresponding qml source file. I would like to know which part of your open source code is responsible for these two functions?
a. GammaRay captures changing text content on the same control.
b. Each control's object tree and its corresponding qml file path can be found.

Looking forward to your reply, I would greatly appreciate it！

**Comment by LWYgut** [comment]
Looking forward to your reply, I would greatly appreciate it！

**Comment by Waqar144** [comment]
Hi, there. The first one is a really broad question and not sure how to answer that. Gammaray is usually (not alway) divided into a server and client. The server is injected in the application being inspected and the client is used to see and modify things at runtime. We have different plugins that handle different modules of Qt e.g., [widgets](https://github.com/KDAB/GammaRay/tree/3.1/plugins/widgetinspector) and [quick inspector](https://github.com/KDAB/GammaRay/tree/3.1/plugins/quickinspector)

Every feature is split into a UI part and the backend part which is actually responsible for making the change in the app being inspected. E.g., we have PropertyAdaptors in the backend and PropertyEditors on the UI side.

I would suggest you to read individual commits or PRs adding a feature to see how things are done rather than reading the source code raw.
