### ISSUE TITLE
Wrong injector ABI

### ISSUE THREAD

**Issue by CComparon** [KDAB/GammaRay#191]
Hi,

I am under Win7 x64, successfully built GammaRay from source in debug (msvc10 x64) and installed it.
However in the Self Test tab of GammaRay Launcher, I see that the (only) found probe is for ABI qt5_4-MSVC-x86_64, where it should be qt5_4-MSVC-x86_64**d**.
It results that when trying to use GammaRay on a debug build of the projet I want to inspect, I get the following error:
> C:\Program Files\GammaRay\bin>gammaray --listen 127.0.0.1 C:\...\MyProject64d.exe
No probe found for ABI qt5_4-MSVC-x86_64d

Many thanks and keep up the great work,
Cyril

**Comment by krf** [comment]
@vkrause: @pasnox: You've recently been touching this code. Do you think we need to append 'd' to the output name of the probe if GammaRay is built in debug mode?

**Comment by winterz** [comment]
for the record, I just built the master branch on Windows8 with Qt5.5.0 in debug mode.
In the self-test I see:
Found valid probe for ABI qt5_5-MSVC-x86_64d at c:\blah\blah

so looks like the "d" is appended 
In fact, looking at the CMakeLists.txt I see this is indeed fixed in master.
Not fixed in the 2.4.x releases though.

**Comment by winterz** [comment]
i'm closing this as fixed in the upcoming 2.5.0 release.
