### ISSUE TITLE
Add "Show Containing Folder" item to Resources view context menu

### ISSUE THREAD

**Issue by mitchcurtis** [KDAB/GammaRay#366]
Currently the only option is Save As:

![screenshot 2017-05-26 12 45 09](https://cloud.githubusercontent.com/assets/6002340/26491821/6df4258c-4211-11e7-97e8-4ad604eaccae.png)

**Comment by chsterz** [comment]
Hi Mitch,
I am not sure what you exactly want here :)

**First Interpretation: Open this file's original folder on disk**
If you want to see the file on your local hard-drive, then GammaRay cannot help you :(
The reason is, that once Qt packs resources into an executable—which is what we inspect in the resources view—all information about the origin of the included files are discarded and instead replaced with symbolic, qrc-specific locations which look something like `":/qt-project.org/styles/commonstyle/images/viewdetailed-16.png"`.

The only way for you to find these files again, is to find them manually on your disk with your OS'es tools.
This can be done based on the files name (use `find` and similar tools)
Or if you are searching for images looking exactly the same, but which were renamed when packed to qrc, you can first Save them and then use tools like `findimagedupes` to find image-duplicates on your disk.

**Second Interpretation: Open the folders like shown in this treeview in my File Manager**
If your issue was to have a folder with the _symbolic structure_ of all the resources (a copy of the tree-views structure) then just select the topmost root entry and save this to somewhere on disk (`/tmp/` or so).

Hope, I could help you here.

**Comment by mitchcurtis** [comment]
Yeah, I didn't really think that through... haha. Oh well.
