### ISSUE TITLE
libgammaray?

### ISSUE THREAD

**Issue by vadi2** [KDAB/GammaRay#496]
Hi,

Is it possible to embed the Qt Widget inspector part of Gammaray into another application? We have one that allows users to script the creation of custom labels and qwidgets, and having a picker-like functionality like the browser offers would be a fantastic help for debugging.

**Comment by vkrause** [comment]
There is the option to embed the GammaRay client into another application, mainly for IDE integration. The Qt Creator plugin uses that for example. It embeds the various tools separately, so just showing the widget inspector should be doable, but not sure if that would be fine-grained enough for your use-case. 
This also assumes out-of-process use, embedding the GammaRay UI into the inspected application itself that way is mostly uncharted territory. There's still the remains of the original in-process mode though, so that's not entirely unthinkable.

**Comment by vadi2** [comment]
Excellent, thanks! I will be exploring this in the future.
