### ISSUE TITLE
Selecting "Graphic Scenes" when debugging Dolphin crashes GammaRay

### ISSUE THREAD

**Issue by bogdanbiv** [KDAB/GammaRay#504]
Could not find this crash report in Github

**Start dolphin under gammaray**
bogdanbiv@desk13 ~ $ gammaray dolphin
**click on "Graphic Scenes"**
Wait ~1-2 seconds
Reproduces every time.
Using precompiled GammaRay from repository.
```
bogdanbiv@desk13 ~ $ gammaray dolphin
Detected ABI qt5_11-x86_64, using ABI qt5_11-x86_64.
Using Wayland-EGL
Trying to convert empty KLocalizedString to QString.
Using the 'xdg-shell-v6' shell integration
GammaRay server listening on: tcp://127.0.0.1:11732
Using Wayland-EGL
Using the 'xdg-shell-v6' shell integration
inotify_add_watch("/home/bogdanbiv/.dropbox/aggregation.dbx") failed: "No such file or directory"
Injector error: Process crashed
```

About the environment
```
Dolphin -> About
KDE Frameworks 5.50.0
Qt 5.11.1

OS: Linux (Arch based distro)
Intel VGA drivers
extra/kwayland 5.50.0-1 (kf5) [installed]
extra/kwayland-integration 5.13.5-1 (plasma) [installed]
extra/plasma-wayland-session 5.13.5-2 [installed]
extra/qt5-wayland 5.11.1-1 (qt qt5) [installed]
extra/sddm 0.18.0-1 [installed]
extra/wayland 1.16.0-1 [installed]
community/gammaray 2.9.1-1 [installed]
No Qt development libraries (symbols)
```

**Comment by akreuzkamp** [comment]
Hey, thanks for reporting the issue. Usually, we would ask you to provide a backtrace, in this case I could reproduce the issue right away, though. In fact, this crash is a bug in dolphin-code, only triggered by GammaRay. GammaRay calls application-code in order to provide information about it. Unfortunately that means we have no way to guard against bugs in application-code that only become visible if GammaRay calls it. Unfortunately, there neither is a generic way to tell GammaRay-bugs and application-bugs apart.

I submitted a patch for the dolphin-bug: https://phabricator.kde.org/D17330 :)

**Comment by bogdanbiv** [comment]
Thanks for getting back, explaining what is going on and for reporting the root cause of the triggered error in Dolphin.
 
I guess it is just that I expected errors not to propagate through the gammaray instance. Kind of like gdb / qtcreator should catch dereferencing a null pointer in a debugged client application and not crash along with it.

I hope that some day this should enter the scope of the project. My guess, if I understood correctly, is that this error catching (esp fatal errors) shall help people understand blunders in their own code.
