### ISSUE TITLE
Cannot be used on application that does not start

### ISSUE THREAD

**Issue by yuyichao** [KDAB/GammaRay#613]
I had a test program which simply creates a `QDialog` and `exec` it. However, when I try to run it in gammaray, gammaray window never pop up and the application window is frozen. This is fixed when I put the dialog initialization in a `QTimer::singleShot` callback and run `app.exec()` so I believe this is caused by waiting only for the application to start without handling other cases where the program might be running.

**Comment by ferdnyc** [comment]
I'm not the expert by any means, but I'm not sure how fixable this is.

Even _without_ `gammaray`, your program wouldn't have been running, because programs that don't `app.exec()` haven't started an event loop. Without the event loop, gammaray isn't allowed to run either.

(Modal widgets, like that `QDialog` you opened, are [special-cased](https://doc.qt.io/qt-5/qapplication.html#exec) to run their own local event loop, so they can be run before `exec()` is called. The Qt developers understood that those dialogs may need to display startup-failure information that prevents the program from reaching `exec()`.

But gammaray isn't a modal dialog box, so it sort of _has to_ wait for your app to `exec()` itself. Though I guess perhaps it's possible for gammaray to _also_ run its own event loop. (Even in that case, though, I'm pretty sure it would be useless because there would be no information available from the application for it to introspect. Until its event loop was started, your program wouldn't respond to any of gammaray's probes.
