### ISSUE TITLE
gammaray.qhc not found

### ISSUE THREAD

**Issue by winterz** [KDAB/GammaRay#867]
After building for Qt6 and then running from inside the builddir I see this:

```
$ ./bin/gammaray
Startup: gammaray-launcher
gammaray.qhc not found in "/home/allen/projects/gammaray/build-master-qt6-gcc/lib64/gammaray/libexec/../../..//share/doc/GammaRay"  - help not available
```
however, if I install gammaray and run that version then I don't see the message

Also, I don't see that message from the builddir/bin Qt5 version
```
$ ./bin/gammaray
Startup: gammaray-launcher
```

Note also the Qt5 build has <builddir>//docs/collection/gammaray.qhc while there is no such thing for the Qt6 build.
This leads me to wonder if there's something amiss with the Qt6 docs generation.

**Comment by ferdnyc** [comment]
The docs generation depends, in part, on being able to find the file `qtcore.index`, which is how GammaRay discovers the documentation directory (for linking to system docs). If your Qt6 install doesn't have HTML copies of the documentation (like Fedora's doesn't), you may not have a `qtcore.index` file in your Qt6 docdir.

You can enable documentation generation in Qt6-without-qtcore.index by explicitly setting `QDOC_INDEX_DIR` when configuring, e.g.:

```bash
cmake -B _build -S . -DQT_VERSION_MAJOR=6 \
  -DQDOC_INDEX_DIR=/usr/share/doc/qt6
```
(That's the correct value on Fedora, YMMV as to where the docdir actually is. It's the dir that corresponds to `/usr/share/doc/qt5/`, if Qt5's `qtcore.index` is at `/usr/share/doc/qt5/qtcore/qtcore.index`.)

...GammaRay probably should use some other method of discovering the docdir. Perhaps there's a target in Qt6ToolsTools or the like.

**Comment by ferdnyc** [comment]
So, the issue here is that GammaRay's documentation build uses the `QDOC_INDEX_DIR` to pass an `--indexdir` argument to the `qdoc` command, which is required when using `depends` to link to system docs (as `docs/manual/gammaray-manual.qdocconf` does).

But if the index files aren't there, providing a `QDOC_INDEX_DIR` path is pointless anyway, since the information that qdoc will want isn't actually found there. (Some distros, like Fedora, don't ship documentation packages for their system Qt6 builds, so the information simply doesn't exist anywhere, to be provided.)

And since it is _possible_ to build the GammaRay docs **without** those indexes (at the cost of all links to Qt classes/types/etc. being broken), perhaps what makes the most sense is to just make `QDOC_INDEX_DIR` optional, and only pass the `--indexdir` argument to `qdoc` if it's set because a `qtcore.index` file is actually discovered.

Even installs without documentation will typically have a `global/qt-html-templates-offline.qdocconf` file, as that's part of the `qtbase` install, not the documentation. So, that discovery can probably still be kept as a prereq for building the docs.
