### ISSUE TITLE
Creating a Deployment of Gamma Ray on Windows

### ISSUE THREAD

**Issue by brycegbrazen** [KDAB/GammaRay#906]
Hi all,

I was curious if anyone could guide me through the deployment process for Gamma Ray on Windows. I have done a development install of Gamma Ray by running the following commands listed in the [INSTALL.md](https://github.com/KDAB/GammaRay/blob/v3.0.0/INSTALL.md) file:
```
    cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/path/where/to/install ../path/to/gammaray
    cmake --build .
    cmake --build . --target install
```

However, when I try to double click the created `gammaray-launcher.exe` I'm greeted with errors like this:

![image](https://github.com/KDAB/GammaRay/assets/69012021/db0c2af2-612b-473b-9846-0dd5a8126d90)

I'm pretty new to building C++ projects so I'm not exactly sure what the issue is, but I know that the application is not finding the Qt libraries it needs (which I assume should be provided by bundled DLLs?).

I want to make a deployment of Gamma Ray that is fully standalone and that can be run just by double clicking on the executable in the File Explorer.

I found some information about an executable bundled with Qt called `windeployqt` but I'm not sure if I should be using that to get a standalone deployment of Gamma Ray or if so, how I should go about using it.

**Comment by mattkdab** [comment]
Can you paste the version and location of Qt on your system?

**Comment by brycegbrazen** [comment]
I've got Qt 5.15 installed, and I have it installed at `C:\Qt515`.

**Comment by Waqar144** [comment]
Hi, how you choose to package GammaRay is upto you. If you want to bundle Qt libs with the app or want to use a third party tool, sure. We can help with build errors or any bugs you encounter in GammaRay. 

For questions about windeployqt I would suggest talking to windeployqt guys directly.

**Comment by brycegbrazen** [comment]
@Waqar144 Could we put a little snippet in the `INSTALL.md` file that mentions that packaging Gamma Ray is up to the user? I feel like adding this information there would be helpful.

**Comment by ratijas** [comment]
> Hi, how you choose to package GammaRay is upto you.

Mind if I ask, how do _you_ package your copy of GammaRay? Or any other contributor with a Windows machine for that matter? What are even the options available?

Note that NSIS cpack generator is totally broken at the moment. I have a little patch that fixes it enough to get through the installation, but then GammaRay.exe just refuses to launch without Qt libs. It seems to be a generic issue with Qt + CPack.

FWIW I wouldn't mind just installing something pre-built from winget these days, instead of fiddling with CMake options that haven't been touched in a decade.

**Comment by ratijas** [comment]
The lazy trick is to install Qt into something like `C:\Qt\6.6.3\msvc2019_64` (which, I'm pretty sure is the default for Qt Online Installer), then build and package GammaRay with CPack (apply [my patch to fix icon path](https://github.com/KDAB/GammaRay/pull/1050)), and finally install it into the same Qt directory as in the first step.

Here is my entire build script, adjust paths as necessary:

```powershell
cd D:\Code\GammaRay
New-Item -ItemType Directory -Force -Path build
cd build
$Env:CMAKE_PREFIX_PATH = "C:\Qt\6.6.3\msvc2019_64"

Import-Module "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
Enter-VsDevShell `
    -VsInstallPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" `
    -StartInPath $pwd `
    -Arch amd64 `
    -HostArch amd64

cmake `
    -G Ninja `
    -DCMAKE_BUILD_TYPE=Release `
    -DQT_VERSION_MAJOR=6 `
    -DGAMMARAY_DISABLE_FEEDBACK=ON `
    "-DCMAKE_INSTALL_PREFIX=D:/Code/GammaRay/build/install" `
    ..

cmake --build .

cpack -G NSIS
```

You gonna need:

- Qt, msvc edition used here
- CMake: `winget install -e --id Kitware.CMake`
- Ninja: `winget install -e --id Ninja-build.Ninja`
- Microsoft Visual Studio 2022, BuildTools only is enough
- ~~Pscx PowerShell module: https://github.com/Pscx/Pscx (entirely optional, if you just launch "Developer PowerShell for VS 2022" profile in Windows Terminal instead of manually sourcing the environment from the .bat script)~~

Update: There is a PowerShell native way to set up dev environment with VS 2022 BuildTools. Use that instead of an unmaintained 3rd-party module to hack into .bat environment.
