### ISSUE TITLE
Quick Scenes Not Responding 

### ISSUE THREAD

**Issue by elmewo** [KDAB/GammaRay#907]
When using Quick Scenes, GammaRay does not respond. When clicking to expand items in the object tree, the application crashes without any hints. 
Seems to be related to #490.

I am using the most recent KDE Fedora on X11 and Gammaray 3.0.95 with Qt 6.6.0.

**Comment by Waqar144** [comment]
Do you a have backtrace? Or a sample app with which the issue can be reproduced?

**Comment by ferdnyc** [comment]
#490 was 6 years and innumerable code revisions ago, it seems highly unlikely they're the same issue. (Especially since the user who reported it also subsequently reported it cleared up.)

Where did your GammaRay build come from, @elmewo? Because, the Fedora packaged GammaRay is still Qt5-only (and still 2.99.50), so it can't be a distro build.

**Comment by elmewo** [comment]
Sorry for the late answerr. Without any change the issue is resolved. 
I used the latest github version and it happened with every QML example. However, I did not update Gammaray or whatsoever, but it is working now. Thank you, anyway.
