### ISSUE TITLE
Can't attach to PySide2 Application importing QtCore

### ISSUE THREAD

**Issue by brycegbrazen** [KDAB/GammaRay#954]
Hi all,

I'm writing a Python application using PySide2, and when I add an import of:

```from PySide2 import QtCore```

to the top of the file, Gamma Ray no longer lists the application on the "Attach" tab (and therefore cannot attach to the process). 

Does anyone know why this is the case? Is this a bug?

Here's a tiny example file that shows the issue:
[simple_test.zip](https://github.com/KDAB/GammaRay/files/14439346/simple_test.zip)

# Specs

- Windows 10
- Qt version 5.15.2
- PySide2 PyPi package version 5.15.2.1
- Gamma Ray 3.0.0

**Comment by Waqar144** [comment]
Please try with latest master

**Comment by brycegbrazen** [comment]
@Waqar144 I rebuilt Gamma Ray with latest master [commit](https://github.com/KDAB/GammaRay/commit/abd80cc20acfd85c0509121736931fd5a62b6a25)  and the application still does not appear in the list of processes that Gamma Ray can attach to after adding the `from PySide2 import QtCore` line.

**Comment by Waqar144** [comment]
@brycegbrazen Can you share what are the contents of your PySide2 package. For e.g., on linux on my pc `/usr/lib/python3.11/site-packages/PySide6/` has 

```
/usr/lib/python3.11/site-packages/PySide6/QtConcurrent.abi3.so
/usr/lib/python3.11/site-packages/PySide6/QtCore.abi3.so
... more .so files
```

Also, if possible put a std::cout in `ProbeABIDetector::containsQtCore(const QByteArray &line)` and print out the line when trying to attach to a pyside app. It will make it easier to figure out what's going wrong.

**Comment by brycegbrazen** [comment]
@Waqar144 Inside of the PySide2 package I've got some similar files to the ones you mentioned above but with the `.dll` and `.lib` extensions:
```
pyside2.abi3.dll
pyside2.abi3.lib
... more .dll files
```
I do also see a .dll file specifically for Qt5Core: `Qt5Core.dll`

**Comment by brycegbrazen** [comment]
Unfortunately I'm not sure how to build and launch Gamma Ray in order to see any `std::cout` print statements I add, so I cannot do that part without some guidance.

**Comment by Waqar144** [comment]
@brycegbrazen 

You can add something like the following at the start of `main()` https://github.com/KDAB/GammaRay/blob/master/launcher/app/main.cpp and then launch the app from the Terminal `./bin/gammaray.exe`:
```c++
#include <windows.h>

// Enable on windows to see output in console
if (AttachConsole(ATTACH_PARENT_PROCESS)) {
    if (fileno(stdout) < 0)
        freopen("CON", "w", stdout);
    if (fileno(stderr) < 0)
        freopen("CON", "w", stderr);
}
```

You can also try to use a debugger instead.

---

This is the function that is used to check if the running process uses QtCore https://github.com/KDAB/GammaRay/blob/abd80cc20acfd85c0509121736931fd5a62b6a25/launcher/core/probeabidetector_win.cpp#L185

and then this https://github.com/KDAB/GammaRay/blob/abd80cc20acfd85c0509121736931fd5a62b6a25/launcher/core/probeabidetector_win.cpp#L238 function is used to check the abi.

If anything is going wrong in these two, it won't attach to pyside apps.

For linux the issue was that it was finding `QtCore.abi3.so` and thinking that this was the QtCore library, which it isn't and hence failed to attach. I am assuming that on windows there is a similar issue.

Perhaps you can create a patch that fixes this :)

**Comment by brycegbrazen** [comment]
@Waqar144 Alright I've figured out the issue! For Python Qt apps on Windows, it seems that the Qt application uses the standard `QtCore5.dll` if QtCore is NOT imported in Python, and then switches over to a different file if it IS imported `QtCore.pyd`.

The problem lies in the fact that the code relies on the found file including the Qt major version as shown [here](https://github.com/KDAB/GammaRay/blob/abd80cc20acfd85c0509121736931fd5a62b6a25/launcher/core/probeabidetector_win.cpp#L245). I'm not really sure what to do about this, but this is definitely the issue.

Any ideas on a solve?
